### PR TITLE
switched database to MySql, created the endpoints and controllers for…

### PR DESCRIPTION
**Pull request by qihongw08**
Switched database to MySQL, added commenting and posting endpoints and controllers.

- Look at the comments and posts class, see if there's any properties a comment/post should have.

### CODE REVIEW

**Comment by quntao-z** [comment]
Nice change!

Notes:
Download Springboot and create a quotes_db

**Review by quntao-z — CHANGES_REQUESTED** [review]
Please add back Cors

**Review by qihongw08 — COMMENTED** [review]
Made the changes

**Comment by quntao-z** [comment]
Awesome!

**Review by quntao-z — APPROVED** [review]

**Pull request merged**
